services:
  redis:
    image: redis:7-alpine
    container_name: my-redis-broker-rss
    ports:
      - "6379:6379"
    networks:
      - rss_feed_network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rss_feed_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - rss_feed_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  fastapi:
    build: .
    container_name: rss_feed_fastapi
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - rss_feed_network
    volumes:
      - .:/app
  
  worker:
    build: .
    container_name: finance_api_worker
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - .:/app 
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - rss_feed_network
  beat:
    build: .
    container_name: finance_api_beat
    command: celery -A app.celery_worker.celery_app beat --loglevel=info

    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - rss_feed_network

volumes:
  postgres_data:

networks:
  rss_feed_network:
    driver: bridge
