"""Subscriptions update

Revision ID: 5d677ce8cd29
Revises: 3196ab48b28d
Create Date: 2025-09-18 14:05:50.170867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d677ce8cd29'
down_revision: Union[str, Sequence[str], None] = '3196ab48b28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_users_to_feeds',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feed_id')
    )
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], name=op.f('subscriptions_feed_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'feed_id', name=op.f('subscriptions_pkey'))
    )
    op.drop_table('subscription_users_to_feeds')
    # ### end Alembic commands ###
