"""Subscriptions updated id

Revision ID: ccb922df74d2
Revises: 5d677ce8cd29
Create Date: 2025-09-18 14:14:01.252757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb922df74d2'
down_revision: Union[str, Sequence[str], None] = '5d677ce8cd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_users_to_feeds', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_users_to_feeds', 'id')
    # ### end Alembic commands ###
