"""Add cascade delete from feeds to articles

Revision ID: fd03d1e06db0
Revises: fa3fd842d01d
Create Date: 2025-09-22 18:07:23.460180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd03d1e06db0'
down_revision: Union[str, Sequence[str], None] = 'fa3fd842d01d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_feed_id_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_feed_id_fkey'), 'articles', 'feeds', ['feed_id'], ['id'])
    # ### end Alembic commands ###
